<?php

namespace App\Models\Lead; // Or App\Models

use Illuminate\Database.Eloquent\Factories\HasFactory;
use Illuminate\Database.Eloquent\Model;
use Illuminate\Database.Eloquent\SoftDeletes;
use Illuminate\Database.Eloquent\Relations\HasMany;
use App\Enums\Lead\CampaignStatus;

class Campaign extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'campaigns';
    protected $guarded = [];

    protected $casts = [
        'status' => CampaignStatus::class,
        'metadata' => 'array',
        'start_date' => 'datetime',
        'end_date' => 'datetime',
    ];

    /**
     * Get all packages associated with this campaign.
     */
    public function packages(): HasMany
    {
        return $this->hasMany(\App\Models\Lead\CampaignPackage::class, 'campaign_id');
    }

    /**
     * Get all leads generated by this campaign.
     */
    public function leads(): HasMany
    {
        return $this->hasMany(\App\Models\Lead\CampaignLead::class, 'campaign_id');
    }
}
