<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Http\Resources\UserResource;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Log;

class AgentAuthController extends BaseController
{
    public function googleLogin(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'credential' => 'required|string',
        ]);
        if ($validator->fails()) {
            return $this->sendError('Validation Error.', $validator->errors(), 422);
        }

        // Verify the Google ID token via Google's tokeninfo endpoint (no extra dependency).
        $payload = null;
        try {
            $client = new Client();
            $resp = $client->get('https://oauth2.googleapis.com/tokeninfo', [
                'query' => ['id_token' => $request->input('credential')],
                'http_errors' => false,
            ]);
            if ($resp->getStatusCode() === 200) {
                $payload = json_decode((string) $resp->getBody(), true);
            }
        } catch (\Exception $e) {
            Log::error('Google tokeninfo failed', ['error' => $e->getMessage()]);
        }

        if (!is_array($payload)) {
            return $this->sendError('Invalid Google token.', [], 401);
        }
        if (($payload['aud'] ?? null) !== config('services.google.client_id')) {
            return $this->sendError('Invalid Google token (audience).', [], 401);
        }
        $emailVerified = $payload['email_verified'] ?? false;
        if ($emailVerified !== true && $emailVerified !== 'true') {
            return $this->sendError('Google email not verified.', [], 401);
        }
        $email = $payload['email'] ?? null;
        if (empty($email)) {
            return $this->sendError('Invalid Google token (email).', [], 401);
        }
        $name = $payload['name'] ?? $email;

        $user = User::where('email', $email)->first();
        if ($user) {
            if ($user->type !== 'agent') {
                return $this->sendError('This email is already in use.', [], 422);
            }
            if ($user->status !== 'active') {
                return $this->sendError('Your agent account is not active.', [], 403);
            }
        } else {
            $user = new User();
            $user->name = $name;
            $user->email = $email;
            $user->type = 'agent';
            $user->status = 'active';
            $user->password = null;
            $user->save(); // referral_code auto-generated by the creating hook
        }

        $token = $user->createToken('AgentSite')->plainTextToken;

        return $this->sendResponse([
            'token' => $token,
            'user' => new UserResource($user),
            'needs_onboarding' => is_null($user->onboarded_at),
        ], 'Logged in.');
    }

    public function onboarding(Request $request)
    {
        $user = $request->user();
        if (!$user || $user->type !== 'agent') {
            return $this->sendError('Forbidden.', [], 403);
        }

        $validator = Validator::make($request->all(), [
            'name' => 'nullable|string|max:255',
            'country_code' => 'required|string|max:8',
            'phone_no' => 'required|string|max:32',
            'agree_terms' => 'accepted',
        ]);
        if ($validator->fails()) {
            return $this->sendError('Validation Error.', $validator->errors(), 422);
        }

        if ($request->filled('name')) {
            $user->name = $request->input('name');
        }
        $user->country_code = $request->input('country_code');
        $user->phone_no = $request->input('phone_no');
        $user->onboarded_at = now();
        $user->save();

        return $this->sendResponse(new UserResource($user), 'Onboarding complete.');
    }
}
