<?php

namespace App\Data\System;

use Spatie\LaravelData\Data;
use Spatie\LaravelData\Lazy;
use Carbon\Carbon;

/**
 * This DTO is for *displaying* notifications.
 * Notifications are not created via a standard API,
 * but are generated by Laravel's Notification system.
 */
class NotificationData extends Data
{
    public function __construct(
        public readonly string $id,
        public readonly string $type,
        public readonly array $data,
        public readonly ?Carbon $read_at,
        public readonly Carbon $created_at,
        public readonly null|Lazy|UserData $user, // Our custom relationship
    ) {}
}
